// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportReport = { requested_sessions: number, inserted_sessions: number, updated_sessions: number, unchanged_sessions: number, };
