// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationKind } from "./OperationKind";
import type { OperationStatus } from "./OperationStatus";

export type Operation = { id: string, kind: OperationKind, status: OperationStatus, canonical_params_hash: string, input_version: string, params_json: unknown, result_json: unknown | null, error_json: unknown | null, submitted_at: string, started_at: string | null, finished_at: string | null, cancel_requested_at: string | null, };
