// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationKind } from "./OperationKind";
import type { OperationStatus } from "./OperationStatus";

export type OperationsListQuery = { status: Array<OperationStatus> | null, kind: Array<OperationKind> | null, limit: number | null, };
