// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tool } from "./Tool";

export type PersistedScanError = { error_id: string, tool: Tool, source_path: string, fingerprint: string | null, message: string, first_seen_at: string, last_seen_at: string, };
