// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RescanReport = { discovered_files: number, skipped_files: number, parsed_sessions: number, not_stored_sessions: number, outdated_sessions: number, up_to_date_sessions: number, scan_errors: number, };
