// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionSyncStatus = "not_stored" | "up_to_date" | "outdated" | "source_missing";
