// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSyncStatus } from "./SessionSyncStatus";
import type { Tool } from "./Tool";

export type SourceSessionView = { session_key: string, tool: Tool, source_session_id: string, source_path: string, source_fingerprint: string, created_at: string | null, source_updated_at: string | null, project_path: string | null, title: string | null, has_subagent_sidecars: boolean, status: SessionSyncStatus, session_uid: string | null, stored_ingested_at: string | null, };
