// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSyncStatus } from "./SessionSyncStatus";
import type { Tool } from "./Tool";

export type StoredSessionView = { status: SessionSyncStatus, session_uid: string, tool: Tool, source_session_id: string, source_path: string, source_fingerprint: string, raw_ref: string, created_at: string | null, source_updated_at: string | null, ingested_at: string, project_path: string | null, title: string | null, has_subagent_sidecars: boolean, };
