// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationKind } from "./OperationKind";
import type { OperationStatus } from "./OperationStatus";

export type SubmitOperationResponse = { operation_id: string, status: OperationStatus, kind: OperationKind, };
