// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provenance of a session's resolved [`title`](SourceSessionView::title).
 *
 * Captured at parse time and round-tripped through the persisted sessions
 * table. `None` (NULL in SQL) means the value is unknown — either because
 * the title itself was missing (no usable source produced one) or because
 * the row was ingested before Phase 6 introduced this field.
 *
 * Invariant maintained by the ingest layer: `title.is_some()` iff
 * `title_source.is_some()`. The reverse direction (consumer code) treats
 * `None` as "unknown source; render no caption".
 */
export type TitleSource = "custom" | "first_user_message" | "slug" | "generated";
