// Hand-rolled toast queue hook.
//
// Per `working/phase-4.md` §Action Bar and Mutation UX, mutation
// outcomes surface as toasts. The queue is small (a handful of
// concurrent notifications at most), so we hold an in-memory array
// and expose `push` + `dismiss` setters. Per the planner brief,
// there is NO auto-dismiss timer — keeping the surface deterministic
// makes the toast assertions in `App.test.tsx` reproducible without
// fake-timer plumbing.
//
// API:
//   - `toasts` — current `ToastEntry[]` (newest first).
//   - `pushToast(toast)` — generates a stable id, prepends the entry,
//     and caps the queue at `maxQueueLength` (default 5). When the
//     cap fires, the OLDEST entry (last in the array) is dropped, so
//     the user always sees the most recent notifications.
//   - `dismissToast(id)` — filters by identity. Idempotent: a
//     duplicate dismiss with an unknown id is a no-op.
//
// React-key stability: each entry's `id` is generated by a
// monotonic counter held in a `useRef` so two pushes in the same
// render tick still get distinct ids and the React reconciler
// doesn't merge them. We do NOT use `crypto.randomUUID()` because
// the test suite runs across both happy-dom and Bun's smallest
// runtime; the counter is portable and zero-dep.

import { useCallback, useRef, useState } from "react";
import type { ToastKind } from "../../components/Toast";

export type ToastEntry = {
  id: string;
  kind: ToastKind;
  title: string;
  message?: string;
  /** Optional retry handler closed over the action context at push
   *  time; callers usually wire this to the same handleX they just
   *  invoked, with the click-time intersection re-derivation rules
   *  baked in (see App.tsx handleImport). */
  onRetry?: () => void;
  details?: import("react").ReactNode;
};

export type UseToastQueueResult = {
  toasts: ToastEntry[];
  /** Prepend a new toast. The id is generated; the caller does not
   *  supply one. */
  pushToast: (toast: Omit<ToastEntry, "id">) => void;
  /** Filter the toast with the given id out of the queue. Idempotent. */
  dismissToast: (id: string) => void;
};

const DEFAULT_MAX_QUEUE_LENGTH = 5;

export function useToastQueue(
  maxQueueLength = DEFAULT_MAX_QUEUE_LENGTH,
): UseToastQueueResult {
  const [toasts, setToasts] = useState<ToastEntry[]>([]);
  // Counter ref ensures id stability across concurrent pushes in the
  // same render tick. The `id` shape is internal and not visible to
  // the user; it just has to be unique for React's reconciler.
  const idCounterRef = useRef(0);

  const pushToast = useCallback(
    (toast: Omit<ToastEntry, "id">) => {
      idCounterRef.current += 1;
      const id = `toast-${idCounterRef.current}`;
      const entry: ToastEntry = { ...toast, id };
      setToasts((prev) => {
        const next = [entry, ...prev];
        // Cap the queue so a chatty user (or a buggy retry loop)
        // can't grow it without bound. Newest-first means slicing
        // from the front preserves the most recent notifications.
        if (next.length > maxQueueLength) {
          return next.slice(0, maxQueueLength);
        }
        return next;
      });
    },
    [maxQueueLength],
  );

  const dismissToast = useCallback((id: string) => {
    setToasts((prev) => {
      // Identity-filter; if no match, return the same reference so
      // downstream consumers don't re-render unnecessarily.
      const next = prev.filter((t) => t.id !== id);
      return next.length === prev.length ? prev : next;
    });
  }, []);

  return { toasts, pushToast, dismissToast };
}
